swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /clue:
    get:
      operationId: "handler.clue.read"
      tags:
        - "Clue"
      summary: "The crossword answer data structure supported by the server application"
      description: "Read the list of crossword clues"
      parameters:
        - name: clue_id
          in: query
          description: Id of the person to get
          type: integer
        - name: date
          in: query
          description: Date
          type: string
        - name: year
          in: query
          description: Year
          type: string
        - name: day
          in: query
          description: Day of week
          type: string
      responses:
        200:
          description: "Successful read clue list operation"
          schema:
            type: "array"
            items:
              properties:
                clue:
                  type: "string"
                date:
                  type: "string"
                source:
                  type: "string"
                answer:
                  type: array
  /clue/search/{keyword}:
      get:
        operationId: "handler.clue.search_clue"
        tags:
          - "Clue Search"
        summary: "The crossword answer data structure supported by the server application"
        description: "Read the list of crossword clues"
        parameters:
          - name: keyword
            in: path
            description: word to search for
            type: string
            required: True
        responses:
          200:
            description: "Successful searched clue list operation"
            schema:
              type: "array"
              items:
                properties:
                  clue:
                    type: "string"
                  date:
                    type: "string"
                  source:
                    type: "string"
                  answer:
                    type: array
  /answer/all:
    get:
      operationId: "handler.answer.read_all"
      tags:
        - "Answer"
      summary: "The crossword answer data structure supported by the server application"
      description: "Read the list of crossword answers"
      parameters:
        - in: query
          name: size
          description: Id of the person to get
          required: False
          type: string
        - in: query
          name: page
          description: Date
          type: string
          required: False
      responses:
        200:
          description: "Successful read answer list operation"
          schema:
            type: "array"
            items:
              properties:
                answer:
                  type: string
                answer_id:
                  type: integer
                clue:
                  type: "array"
                  items:
                    properties:
                      clue:
                        type: string
                      clue_id:
                        type: "string"
                      date:
                        type: "string"
                      source:
                        type: "string"
  /answer/search/{keyword}:
    get:
      operationId: "handler.answer.search_answer"
      tags:
        - "Answer"
      summary: "The crossword answer data structure supported by the server application"
      description: "Read the list of crossword answers"
      parameters:
        - name: keyword
          in: path
          description: word to search for
          type: string
          required: True
      responses:
        200:
          description: "Successful one answer based on id"
          schema:
            type: "object"
            items:
              properties:
                source:
                  type: "string"
                clue:
                  type: "array"
                  items:
                    properties:
                      clue_id:
                        type: "integer"
                      clue:
                        type: "string"
                      date:
                        type: "string"
                      source:
                        type: "string"